package io.github.cottonmc.functionapi.api.content.block.enums

enum class BlockSoundGroup {
    STONE,BAMBOO, BAMBOO_SAPLING, CORAL, CROP, GLASS, GRASS, GRAVEL, LADDER, LANTERN, METAL, NETHER_WART, SAND, SCAFFOLDING, SLIME, SNOW, STEM, SWEET_BERRY_BUSH, WET_GRASS, WOOD, WOOL, ANVIL
}